// University of Kelaniya Canteen Data Model.
// All dishes reflect actual meals prepared and served in the student cafeterias.
// Subsidized prices are set according to student welfare rates in Sri Lankan Rupees (LKR).

export const CANTEEN_INFO = {
  name: 'University of Kelaniya Main Canteen',
  location: 'Opposite Faculty of Science, Dalugama Campus',
  operatingHours: '07:30 AM - 05:30 PM',
  notice: 'Please show your digital Order ID at the designated counter during pickup.',
  containerFee: 20, // Eco lunch box container fee in LKR
};

export const MENU_CATEGORIES = [
  { id: 'all', label: 'All Items' },
  { id: 'meals', label: 'Rice & Meals' },
  { id: 'roti', label: 'Roti & Hoppers' },
  { id: 'shorteats', label: 'Short Eats' },
  { id: 'beverages', label: 'Beverages' },
];

export const PICKUP_COUNTERS = [
  {
    id: 'counter-1',
    name: 'Counter 1: Main Meals & Rice',
    description: 'Serving hot rice, lunch plates, and kottu roti',
    location: 'Main Dining Hall - Left Wing',
  },
  {
    id: 'counter-2',
    name: 'Counter 2: Short Eats & Bakery',
    description: 'Serving buns, patties, rolls, and quick snacks',
    location: 'Main Dining Hall - Center Counter',
  },
  {
    id: 'counter-3',
    name: 'Counter 3: Tea & Juice Bar',
    description: 'Serving hot tea, iced milo, faluda, and fresh juices',
    location: 'Veranda Entrance - Right Wing',
  },
];

export const PICKUP_TIME_SLOTS = [
  { id: 'slot-1', label: 'Next Lecture Interval (10:15 AM - 10:30 AM)' },
  { id: 'slot-2', label: 'Main Lunch Break (12:15 PM - 01:00 PM)' },
  { id: 'slot-3', label: 'Afternoon Interval (03:15 PM - 03:30 PM)' },
  { id: 'slot-4', label: 'Express Pickup (Ready in 10-15 Minutes)' },
];

export const MENU_ITEMS = [
  // Rice and Main Meals (Subsidized student rates: 150 - 240 LKR)
  {
    id: 'meal-01',
    name: 'Chicken Kottu Roti',
    category: 'meals',
    price: 240,
    preparationTime: '10 mins',
    dietary: 'Non-Vegetarian',
    spiceLevel: 'Spicy',
    description: 'Chopped godamba roti stir-fried on the hot griddle with spiced chicken pieces, scrambled egg, leeks, carrots, and aromatic curry gravy.',
    ingredients: 'Godamba roti, chicken, egg, leeks, onions, spices',
    calories: '480 kcal',
    counter: 'Counter 1',
    popular: true,
  },
  {
    id: 'meal-02',
    name: 'Vegetable Fried Rice with Chilli Paste',
    category: 'meals',
    price: 180,
    preparationTime: '8 mins',
    dietary: 'Vegetarian',
    spiceLevel: 'Medium',
    description: 'Wok-tossed basmati rice with freshly diced carrots, leeks, and spring onions, accompanied by traditional fiery canteen chilli paste.',
    ingredients: 'Basmati rice, carrots, leeks, homemade chilli paste',
    calories: '390 kcal',
    counter: 'Counter 1',
    popular: true,
  },
  {
    id: 'meal-03',
    name: 'Chicken Rice and Curry (Student Plate)',
    category: 'meals',
    price: 220,
    preparationTime: '5 mins',
    dietary: 'Non-Vegetarian',
    spiceLevel: 'Spicy',
    description: 'Wholesome plate of samba rice served with spicy country chicken curry, tempered dhal, curried potato, and freshly ground coconut sambol.',
    ingredients: 'Samba rice, chicken curry, dhal, potato, pol sambol',
    calories: '520 kcal',
    counter: 'Counter 1',
    popular: true,
  },
  {
    id: 'meal-04',
    name: 'Subsidized Vegetable Rice and Curry',
    category: 'meals',
    price: 150,
    preparationTime: '5 mins',
    dietary: 'Vegetarian',
    spiceLevel: 'Medium',
    description: 'Traditional campus lunch plate with steamed rice, yellow lentil dhal, tempered beans, beetroot curry, and crispy papadam.',
    ingredients: 'Steamed rice, dhal, seasonal vegetables, papadam',
    calories: '360 kcal',
    counter: 'Counter 1',
    popular: false,
  },
  {
    id: 'meal-05',
    name: 'Egg Fried Rice with Devilled Sauce',
    category: 'meals',
    price: 190,
    preparationTime: '8 mins',
    dietary: 'Vegetarian with Egg',
    spiceLevel: 'Medium',
    description: 'Fluffy fried rice tossed with scrambled egg and crisp vegetables, served with rich sweet-and-spicy devilled onion gravy.',
    ingredients: 'Fried rice, egg, leeks, devilled gravy',
    calories: '420 kcal',
    counter: 'Counter 1',
    popular: false,
  },
  {
    id: 'meal-06',
    name: 'Fish Rice and Curry',
    category: 'meals',
    price: 180,
    preparationTime: '5 mins',
    dietary: 'Pescatarian',
    spiceLevel: 'Spicy',
    description: 'Plate of steamed rice with authentic sour fish ambul thiyal or fish curry, tempered dhal, and fresh gotukola sambol.',
    ingredients: 'Rice, tuna ambul thiyal, dhal, gotukola sambol',
    calories: '440 kcal',
    counter: 'Counter 1',
    popular: false,
  },

  // Roti and Traditional Delicacies (120 - 160 LKR)
  {
    id: 'roti-01',
    name: 'Egg Roti with Spiced Dhal & Lunu Miris',
    category: 'roti',
    price: 150,
    preparationTime: '6 mins',
    dietary: 'Vegetarian with Egg',
    spiceLevel: 'Spicy',
    description: 'Fresh griddle-folded flatbread with a whole cooked egg inside, paired with creamy yellow lentil dhal and crushed red onion chilli sambol.',
    ingredients: 'Wheat flatbread, egg, yellow dhal, red onions, chilli',
    calories: '320 kcal',
    counter: 'Counter 1',
    popular: true,
  },
  {
    id: 'roti-02',
    name: 'String Hoppers (Set of 10) with Kiri Hodi',
    category: 'roti',
    price: 160,
    preparationTime: '5 mins',
    dietary: 'Vegetarian',
    spiceLevel: 'Mild',
    description: 'Ten freshly steamed red and white rice flour noodle nests, served with aromatic coconut milk gravy (kiri hodi) and spicy pol sambol.',
    ingredients: 'Rice flour, coconut milk, curry leaves, pol sambol',
    calories: '310 kcal',
    counter: 'Counter 1',
    popular: true,
  },
  {
    id: 'roti-03',
    name: 'Pol Roti with Lunu Miris (2 Pieces)',
    category: 'roti',
    price: 120,
    preparationTime: '5 mins',
    dietary: 'Vegetarian',
    spiceLevel: 'Very Spicy',
    description: 'Thick, rustic flatbreads made with freshly grated coconut and flour, toasted to a golden crust and served with hot lunu miris.',
    ingredients: 'Grated coconut, flour, red onions, dried chilli, lime',
    calories: '340 kcal',
    counter: 'Counter 1',
    popular: false,
  },

  // Short Eats and Bakery (50 - 80 LKR)
  {
    id: 'short-01',
    name: 'Spicy Fish Bun (Malu Paan)',
    category: 'shorteats',
    price: 80,
    preparationTime: 'Instant',
    dietary: 'Pescatarian',
    spiceLevel: 'Medium',
    description: 'Classic Sri Lankan triangular baked bread roll filled with savory curried canned fish, boiled potatoes, and black pepper.',
    ingredients: 'Baked bun, fish, potatoes, black pepper, onions',
    calories: '220 kcal',
    counter: 'Counter 2',
    popular: true,
  },
  {
    id: 'short-02',
    name: 'Crispy Egg and Vegetable Roll',
    category: 'shorteats',
    price: 70,
    preparationTime: 'Instant',
    dietary: 'Vegetarian with Egg',
    spiceLevel: 'Medium',
    description: 'Crispy golden breadcrumb-crusted Chinese roll packed with boiled egg slice and curried vegetable filling.',
    ingredients: 'Breadcrumbs, egg, curried potatoes, carrots',
    calories: '190 kcal',
    counter: 'Counter 2',
    popular: true,
  },
  {
    id: 'short-03',
    name: 'Ulundu Vadai with Chutney',
    category: 'shorteats',
    price: 60,
    preparationTime: 'Instant',
    dietary: 'Vegetarian',
    spiceLevel: 'Mild',
    description: 'Deep-fried savory doughnut made of ground black gram lentils, curry leaves, and green chillies, served with fresh coconut chutney.',
    ingredients: 'Ulundu flour, green chillies, curry leaves, coconut chutney',
    calories: '150 kcal',
    counter: 'Counter 2',
    popular: false,
  },
  {
    id: 'short-04',
    name: 'Fish Patty',
    category: 'shorteats',
    price: 60,
    preparationTime: 'Instant',
    dietary: 'Pescatarian',
    spiceLevel: 'Medium',
    description: 'Flaky half-moon pastry shell stuffed with spicy minced fish, mashed potatoes, and diced onions.',
    ingredients: 'Flaky pastry, fish stuffing, potatoes, spices',
    calories: '160 kcal',
    counter: 'Counter 2',
    popular: false,
  },
  {
    id: 'short-05',
    name: 'Vegetable Samosa',
    category: 'shorteats',
    price: 50,
    preparationTime: 'Instant',
    dietary: 'Vegetarian',
    spiceLevel: 'Mild',
    description: 'Crisp triangular fried turnover stuffed with spiced potatoes, green peas, and carrots.',
    ingredients: 'Pastry sheet, potatoes, green peas, curry powder',
    calories: '130 kcal',
    counter: 'Counter 2',
    popular: false,
  },

  // Beverages and Drinks (30 - 150 LKR)
  {
    id: 'bev-01',
    name: 'Hot Ginger Plain Tea (Kahata)',
    category: 'beverages',
    price: 30,
    preparationTime: '3 mins',
    dietary: 'Vegetarian',
    spiceLevel: 'Mild',
    description: 'Freshly brewed strong Ceylon black tea infused with crushed hot ginger, served with a piece of natural palm jaggery.',
    ingredients: 'Ceylon black tea, crushed fresh ginger, hot water, jaggery',
    calories: '25 kcal',
    counter: 'Counter 3',
    popular: true,
  },
  {
    id: 'bev-02',
    name: 'Ceylon Milk Tea (Kiri The)',
    category: 'beverages',
    price: 60,
    preparationTime: '3 mins',
    dietary: 'Vegetarian',
    spiceLevel: 'None',
    description: 'Traditional Sri Lankan milk tea prepared with rich Ceylon tea blend and creamy sweetened condensed milk.',
    ingredients: 'Tea, condensed milk, sugar',
    calories: '95 kcal',
    counter: 'Counter 3',
    popular: true,
  },
  {
    id: 'bev-03',
    name: 'Iced Milo with Extra Powder',
    category: 'beverages',
    price: 140,
    preparationTime: '4 mins',
    dietary: 'Vegetarian',
    spiceLevel: 'None',
    description: 'The campus canteen favourite: chilled chocolate malt drink poured over ice and topped with a generous spoonful of dry Milo powder.',
    ingredients: 'Milo malt powder, milk, ice, sugar',
    calories: '180 kcal',
    counter: 'Counter 3',
    popular: true,
  },
  {
    id: 'bev-04',
    name: 'Rose Syrup Faluda',
    category: 'beverages',
    price: 150,
    preparationTime: '5 mins',
    dietary: 'Vegetarian',
    spiceLevel: 'None',
    description: 'Chilled rose-scented milk drink layered with swollen basil seeds (kasakasa), grass jelly noodles, and sweetened milk.',
    ingredients: 'Rose syrup, milk, basil seeds, grass jelly, sugar',
    calories: '210 kcal',
    counter: 'Counter 3',
    popular: true,
  },
  {
    id: 'bev-05',
    name: 'Fresh Lime Juice with Soda',
    category: 'beverages',
    price: 100,
    preparationTime: '3 mins',
    dietary: 'Vegetarian',
    spiceLevel: 'None',
    description: 'Freshly squeezed local lime juice blended with chilled sparkling soda water, sugar syrup, and a pinch of salt for instant hydration.',
    ingredients: 'Fresh lime, soda water, sugar syrup, pinch of salt',
    calories: '65 kcal',
    counter: 'Counter 3',
    popular: false,
  },
];
